version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cancer_compass
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - redis
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  ai:
    build: ./ai
    volumes:
      - ./ai/data:/app/data
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
